### ISSUE TITLE
Automated builds and release

### ISSUE THREAD

**Issue by drpaneas** [romie-gr/romie#16]
#### Description

Whenever there is a new release, we want to automatically build and release. Create the bare minimum configuration and pipeline to achieve that for a Go project that is using **go modules**.

#### Acceptance Criteria

- [x] Use https://github.com/marketplace/actions/goreleaser-action
- [x] Create the `.goreleaser.yml`
- [x] Create a `build` workflow that builds and releases the artifacts. It gets triggered when:

```yml
on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:
```

Complexity: 3
