### ISSUE TITLE
Create changelog automatically

### ISSUE THREAD

**Issue by drpaneas** [romie-gr/romie#36]
#### Description

It's a common practice to have a changelog, even though nobody reads it. But well ...

####Acceptance Criteria

Using goreleaser:

- [ ] Sort all the commits since the last release
- [ ] Exclude commits that start in the title with `docs` or `test` or `Merge pull request` or `Merge branch` or `go mod tidy`.

** or alternatively** try this:

#### Acceptance Criteria

- [ ] Install https://github.com/marketplace/actions/changelog-ci
- [ ] Test it

**Comment by drpaneas** [comment]
@cerebrux I think you have something already made. Hm?

**Comment by drpaneas** [comment]
Depends on #69

**Comment by cerebrux** [comment]
> @cerebrux I think you have something already made. Hm?

I was thinking to implement something like this, but I don't remember actually doing it :P.

So let me check it :)

**Comment by cerebrux** [comment]
I have no Idea how my fork closed this issue ! LOL

**Comment by zoispag** [comment]
> I have no Idea how my fork closed this issue ! LOL

![image](https://user-images.githubusercontent.com/21138205/96368821-8e77af00-1156-11eb-8e3b-5361068c4d2a.png)

😅

**Comment by cerebrux** [comment]
I was wondering why the:
```
Acceptance Criteria
 Install https://github.com/marketplace/actions/changelog-ci
```
was not working in my tests.... then I read again its documentation:
_[..]changelog is prepended to CHANGELOG.md file and committed and/or commented **to the release Pull request**._

So... this one probably goes to "κουβά" as we don't need every pull request to be populated with changelog... or do we ?

**Comment by ktsamis** [comment]
@cerebrux 
You didn't use the https://github.com/marketplace/actions/changelog-ci, I see [here](https://github.com/cerebrux/romie/pull/4/files) that you created goreleaser. You need to read the [documentation](https://github.com/marketplace/actions/changelog-ci) and create the CHANGELOG/md file initially (I think, it might not be necessary but for safety I would say let's) then create /edit the `.github/workflows/workflow.yml` file and add the step:

```
name: Changelog CI

# Controls when the action will run. Triggers the workflow on a pull request
on:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository
      - uses: actions/checkout@v2

      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v0.7.0
        with:
          changelog_filename: CHANGELOG.md
          config_file: changelog-ci-config.json
        # Add this if you are using it on a private repository
        # Or if you have turned on commenting through the config file.
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
```
if you want to use the [default conf options](https://github.com/marketplace/actions/changelog-ci#configuration-options) then skip the config_file declaration.
