### ISSUE TITLE
Convert TODO into an issue

### ISSUE THREAD

**Issue by drpaneas** [romie-gr/romie#39]
#### Description

Sometimes devs use the keyword `TODO` in the source code in order to remind themselves to come back and fix that. Yeah, this never happens because they forget about it. Make sure they don't, by having a bot looking for that and creating a GH issue for it automatically.

#### Acceptance Criteria

- [ ] Install https://github.com/marketplace/actions/todo-actions
- [ ] Test it if it works and how it looks like. What labels can be applied, etc...

**Comment by cerebrux** [comment]
I am assigning you as you will need a free mongodb instance and add some secrets in the settings of the repository see: https://github.com/marketplace/actions/todo-actions#before-you-start

**Comment by zoispag** [comment]
I am using this one: [TODO Bot](https://todo.jasonet.co/)
with the following config:

```yml
# Integrate todo bot (https://github.com/probot/probot)
# https://todo.jasonet.co/
todo:
  keyword: ["@todo", "TODO"] # string|string[]
  bodyKeyword: ["@body", "BODY"] # string|string[]
  blobLines: 5                # number|boolean, 0 or false to disable
  autoAssign: true            # string|string[]|boolean
  label: true                 # boolean|string|string[]
  reopenClosed: false         # boolean
```

It works great. I do not have permissions to "install" integrations in this repo.
