### ISSUE TITLE
Run 'go mod tidy' automatically

### ISSUE THREAD

**Issue by drpaneas** [romie-gr/romie#7]
#### Description
Whenever there is a new version of the 3rd party dependencies used by the project (namely whatever is inside `go.mod` and `go.sum`) then let the project update itself without developer's intervention.

#### Test the first way

https://github.com/marketplace/actions/go-mod-tidy-pr-go-1-13-4

#### Test the second way

- [ ] Learn about [dependabot](https://dependabot.com/) which is available also at GitHub Marketplace [here](https://github.com/marketplace/dependabot-preview)
- [ ] Write a GH Action workflow doing the following:
- [ ] runs on `push` for the `master` branch`
- [ ] gets triggered when `go.mod`, `go.sum` or the `.github/workflow/<name>.yml` has been modified.
- [ ] fetches the project using [actions/checkout](https://github.com/actions/checkout)
- [ ] sets up Go 1.15 via [actions/setup-go](https://github.com/actions/setup-go)
- [ ] Make sure it runs this snippet:

```yml
        name: Tidy
        run: |
          rm -f go.sum
          go mod tidy
```
 
After updating those files, it prepares a PR from `go-mod-tidy` branch, that gets automatically thanks to the `automerge` labels. For creating the PR as part of the same GH action use this, with the following settings:

 - [ ] create a PR using [actions/create-pull-request](https://github.com/peter-evans/create-pull-request) with:

```yml
        name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(deps): go mod tidy"
          title: "chore(deps): go mod tidy"
          body: |
            Current `go.mod` and `go.sum` don't match the source code.
          branch: go-mod-tidy
          branch-suffix: timestamp
          labels: automerge
```

#### Feedback

Which of the two ways is better? Please provide pros and cons

Complexity: 8
